# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install tox-travis coveralls

# command to run tests using coverage, e.g. python setup.py test
script:
  - tox

after_success:
  - coveralls
